# Generated by Django 3.1.6 on 2021-02-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('respostas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respostas.resposta')),
            ],
        ),
    ]
