# Generated by Django 3.1.6 on 2021-02-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_auto_20210201_2339'),
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta'),
            preserve_default=False,
        ),
    ]
