# Generated by Django 3.1.6 on 2021-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
